-- Optional cross-machine memory for onebot-llm-bridge.
-- Run this in a private Supabase project. No chat data is included here.

create table if not exists bridge_messages (
  id bigint generated by default as identity primary key,
  bot_qq text not null,
  conversation_key text not null,
  conversation_type text not null check (conversation_type in ('private', 'group')),
  conversation_id text not null,
  sender_id text not null,
  sender_name text not null default '',
  source_message_id text not null,
  is_self boolean not null default false,
  content_text text not null default '',
  segments jsonb not null default '[]'::jsonb,
  reply_to text,
  occurred_at bigint not null,
  created_at timestamptz not null default now(),
  unique (bot_qq, conversation_key, source_message_id)
);

create index if not exists bridge_messages_context_idx
  on bridge_messages (bot_qq, conversation_key, occurred_at desc, id desc);

create table if not exists bridge_facts (
  id bigint generated by default as identity primary key,
  bot_qq text not null,
  scope_key text not null,
  fact text not null,
  source_message_id text not null default '',
  created_at timestamptz not null default now(),
  unique (bot_qq, scope_key, fact)
);

create index if not exists bridge_facts_scope_idx
  on bridge_facts (bot_qq, scope_key, id desc);

create table if not exists bridge_smart_groups (
  id bigint generated by default as identity primary key,
  bot_qq text not null,
  group_id text not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (bot_qq, group_id)
);

create table if not exists bridge_summaries (
  id bigint generated by default as identity primary key,
  bot_qq text not null,
  conversation_key text not null,
  version integer not null,
  summary text not null,
  created_at timestamptz not null default now(),
  unique (bot_qq, conversation_key, version)
);

create index if not exists bridge_summaries_latest_idx
  on bridge_summaries (bot_qq, conversation_key, version desc);

create table if not exists bridge_leases (
  bot_qq text not null,
  conversation_key text not null,
  owner_id text not null,
  lease_until bigint not null,
  primary key (bot_qq, conversation_key)
);

create index if not exists bridge_leases_expiry_idx
  on bridge_leases (lease_until);

-- This is a server-side credential schema. Restrict it to the secret key or
-- add project-specific RLS policies before exposing it to a client key.
revoke all on table bridge_messages, bridge_facts, bridge_smart_groups, bridge_summaries, bridge_leases from anon, authenticated;
grant all on table bridge_messages, bridge_facts, bridge_smart_groups, bridge_summaries, bridge_leases to service_role;
